name: create-release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-package-to-pypi:
    if: github.repository == 'cmlibs/neon'
    runs-on: ubuntu-24.04
    name: Release package
    permissions:
      contents: write
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Release Python package
        uses: hsorby/release-python-package-action@v1
        with:
          pypi-package-name: cmapps.neon
